package captainsly.anvil.mechanics.enums;

public enum EnumSkill {

	ONE_HANDED, TWO_HANDED, LOCKPICKING, PICKPOCKETING, SMITHING, ENCHANTING, LIGHT_MAGIC, DARK_MAGIC, FIRE_MAGIC,
	EARTH_MAGIC, FROST_MAGIC, WATER_MAGIC,

}
